title: "Will Covington's Technical Portfolio"
description: Take your time, slow down and enjoy the view.
author: Will Covington
theme: jekyll-theme-minimal  # Built-in GitHub Pages theme
show_downloads: false
